project:
  type: website

website:
  title: "Yanyang He's Personal Website"
  navbar:
    left:
      - text: About You
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


